apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    annotations:
        app: jenkins
        app.kubernetes.io/instance: jenkins
        app.kubernetes.io/name: jenkins
    name: {{ include "jenkins-cluster-role.name" . }}
rules:
    - apiGroups:
          - ""
      resources:
          - "pods"
          - "pods/exec"
          - "pods/log"
      verbs:
          - "*"
