apiVersion: v1
kind: ConfigMap
metadata:
  name: solsa-cm
  labels:
    "app.kubernetes.io/name": "argocd"
    "app.kubernetes.io/instance": "argocd"
    group: {{ .Values.group | quote }}
data:
  solsa.yaml: |
    clusters:
    - name: 'in-cluster'
      ingress:
        iks:
          subdomain: {{ .Values.ingress.subdomain | quote }}
          tlssecret: {{ .Values.ingress.tlssecret | quote }}
    contexts:
    - name: 'in-cluster-context'
      cluster: 'in-cluster'
