---
# Source: tool-config/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: artifactory-access
  labels:
    app: artifactory
    app.kubernetes.io/name: artifactory
    app.kubernetes.io/instance: "artifactory"
    app.kubernetes.io/version: "0.1.3"
    app.kubernetes.io/part-of: artifactory
    app.kubernetes.io/component: "tools"
    chart: tool-config-0.1.3
    release: "artifactory"
    group: "catalyst-tools"
    grouping: "garage-cloud-native-toolkit"
  annotations:
    description: Secret to hold the username and password for artifactory so that other components can access it
type: Opaque
stringData:
  ARTIFACTORY_PASSWORD: "password"
  ARTIFACTORY_USER: "admin"
  ARTIFACTORY_ADMIN_ACCESS_PASSWORD: "admin"
  ARTIFACTORY_ADMIN_ACCESS_USER: "admin-access"
  ARTIFACTORY_ENCRYPT: ""
---
# Source: tool-config/templates/config-map.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: artifactory-config
  labels:
    app: artifactory
    app.kubernetes.io/name: artifactory
    app.kubernetes.io/instance: "artifactory"
    app.kubernetes.io/version: "0.1.3"
    app.kubernetes.io/part-of: artifactory
    app.kubernetes.io/component: "tools"
    chart: tool-config-0.1.3
    release: "artifactory"
    group: "catalyst-tools"
    grouping: "garage-cloud-native-toolkit"
  annotations:
    description: Config map to hold the url for artifactory in the environment so that other components can access it
data:
  ARTIFACTORY_URL: "https://artifactory-tools.gsi-learning-ocp43-7ec5d722a0ab3f463fdc90eeb94dbc70-0000.us-east.containers.appdomain.cloud"
