---
# Source: tool-config/templates/config-map.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: pactbroker-config
  labels:
    app: pactbroker
    app.kubernetes.io/name: pactbroker
    app.kubernetes.io/instance: "pactbroker-config"
    app.kubernetes.io/version: "0.1.3"
    app.kubernetes.io/part-of: pactbroker
    app.kubernetes.io/component: "tools"
    chart: tool-config-0.1.3
    release: "pactbroker-config"
    group: "catalyst-tools"
    grouping: "garage-cloud-native-toolkit"
  annotations:
    description: Config map to hold the url for pactbroker in the environment so that other components can access it
data:
  PACTBROKER_URL: "https://pact-broker-tools.gsi-learning-ocp43-7ec5d722a0ab3f463fdc90eeb94dbc70-0000.us-east.containers.appdomain.cloud"
