---
# Source: pact-broker/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: pact-broker
  labels:
    app: pact-broker
    app.kubernetes.io/name: pact-broker
    helm.sh/chart: pact-broker-0.1.0
    app.kubernetes.io/instance: pact-broker
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 9292
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: pact-broker
    app.kubernetes.io/instance: pact-broker
---
# Source: pact-broker/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pact-broker
  labels:
    app: pact-broker
    app.kubernetes.io/name: pact-broker
    helm.sh/chart: pact-broker-0.1.0
    app.kubernetes.io/instance: pact-broker
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: pact-broker
      app.kubernetes.io/instance: pact-broker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pact-broker
        app.kubernetes.io/instance: pact-broker
    spec:
      containers:
        - name: pact-broker
          image: "pactfoundation/pact-broker:2.50.1-1"
          imagePullPolicy: IfNotPresent
          env:
            - name: PACT_BROKER_DATABASE_ADAPTER
              value: "sqlite"
            - name: PACT_BROKER_DATABASE_NAME
              value: "pactbroker.sqlite"
            - name: PACT_BROKER_PUBLIC_HEARTBEAT
              value: "true"
            - name: PACT_BROKER_PORT
              value: "9292"
          ports:
            - name: http
              containerPort: 9292
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /diagnostic/status/heartbeat
              port: http
          readinessProbe:
            httpGet:
              path: /diagnostic/status/heartbeat
              port: http
          resources:
            {}
---
# Source: pact-broker/templates/route.yaml
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    openshift.io/host.generated: "true"
  name: pact-broker
spec:
  port:
    targetPort: http
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: pact-broker
