---
# Source: tool-config/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: sonarqube-access
  labels:
    app: sonarqube
    app.kubernetes.io/name: sonarqube
    app.kubernetes.io/instance: "sonarqube"
    app.kubernetes.io/version: "0.1.3"
    app.kubernetes.io/part-of: sonarqube
    app.kubernetes.io/component: "tools"
    chart: tool-config-0.1.3
    release: "sonarqube"
    group: "catalyst-tools"
    grouping: "garage-cloud-native-toolkit"
  annotations:
    description: Secret to hold the username and password for sonarqube so that other components can access it
type: Opaque
stringData:
  SONARQUBE_PASSWORD: "admin"
  SONARQUBE_USER: "admin"
---
# Source: tool-config/templates/config-map.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: sonarqube-config
  labels:
    app: sonarqube
    app.kubernetes.io/name: sonarqube
    app.kubernetes.io/instance: "sonarqube"
    app.kubernetes.io/version: "0.1.3"
    app.kubernetes.io/part-of: sonarqube
    app.kubernetes.io/component: "tools"
    chart: tool-config-0.1.3
    release: "sonarqube"
    group: "catalyst-tools"
    grouping: "garage-cloud-native-toolkit"
  annotations:
    description: Config map to hold the url for sonarqube in the environment so that other components can access it
data:
  SONARQUBE_URL: "https://sonarqube-tools.gsi-learning-ocp43-7ec5d722a0ab3f463fdc90eeb94dbc70-0000.us-east.containers.appdomain.cloud"
