---
# Source: tool-config/templates/config-map.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: apieditor-config
  labels:
    app: "swaggereditor-dashboard"
    app.kubernetes.io/name: "swaggereditor-dashboard"
    app.kubernetes.io/instance: "apieditor"
    app.kubernetes.io/version: "0.1.3"
    app.kubernetes.io/part-of: "swaggereditor-dashboard"
    app.kubernetes.io/component: "tools"
    chart: tool-config-0.1.3
    release: "apieditor"
    group: "catalyst-tools"
    grouping: "garage-cloud-native-toolkit"
  annotations:
    description: Config map to hold the url for apieditor in the environment so that other components can access it
data:
  APIEDITOR_URL: "https://apieditor-tools.gsi-learning-ocp43-7ec5d722a0ab3f463fdc90eeb94dbc70-0000.us-east.containers.appdomain.cloud"
