apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ibmcloud.name" . }}-apikey
  labels:
    app: {{ .Release.Name }}
    group: {{ .Values.group }}
type: Opaque
stringData:
  APIKEY: {{ .Values.apikey | quote }}
