apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    annotations:
        app: jenkins
        app.kubernetes.io/instance: jenkins
        app.kubernetes.io/name: jenkins
    name: {{ include "jenkins-cluster-role.name" . }}
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: {{ include "jenkins-cluster-role.name" . }}
subjects:
    - kind: ServiceAccount
      name: jenkins
      namespace: {{ .Release.Namespace }}
