image:
  pullPolicy: Always

ingress:
  enabled: true
  # Used to create an Ingress record.
#  hosts:
#    - name: sonar.organization.com
  annotations:
   kubernetes.io/ingress.class: nginx
   nginx.ingress.kubernetes.io/proxy-body-size: "20m"
   ingress.kubernetes.io/proxy-body-size: "20M"
   ingress.bluemix.net/client-max-body-size: "20m"

persistence:
  enabled: false

postgresql:
  # Enable to deploy the PostgreSQL chart
  enabled: true
#  postgresUser: "sonarUser"
#  postgresPassword: "sonarPass"
#  postgresDatabase: "sonarDB"
#  postgresServer: ""
#  service:
#    port: 5432

enableTests: false