apiVersion: v1
kind: ConfigMap
metadata:
  name: artifactory-config
  labels:
    "app.kubernetes.io/name": 'artifactory'
    "app.kubernetes.io/instance": "artifactory"
    group: {{ .Values.group }}
data:
  ARTIFACTORY_URL: {{ .Values.url | quote }}
