commonLabels:
 app: "argocd"
resources:
 - base.yaml
 - solsa/solsa-cm.yaml
patchesStrategicMerge:
 - solsa/argocd-reposerver.yaml
 - solsa/argocd-cm.yaml
patchesJson6902:
 - path: patch-dex-deployment.yaml
   target:
     group: apps
     version: v1
     kind: Deployment
     name: argocd-dex-server
 - path: patch-argocd-server.yaml
   target:
     group: apps
     version: v1
     kind: Deployment
     name: argocd-server
