apiVersion: v1
kind: Secret
metadata:
  name: artifactory-access
  labels:
    "app.kubernetes.io/name": 'artifactory'
    "app.kubernetes.io/instance": "artifactory"
    group: {{ .Values.group }}
type: Opaque
stringData:
  ARTIFACTORY_PASSWORD: {{ .Values.password | quote }}
  ARTIFACTORY_USER: {{ .Values.username | quote }}
  ARTIFACTORY_ADMIN_ACCESS_USER: {{ .Values.adminAccessUser | quote }}
  ARTIFACTORY_ADMIN_ACCESS_PASSWORD: {{ .Values.adminAccessPassword | quote }}
  ARTIFACTORY_ENCRPT: {{ .Values.encryptPassword | quote }}
